apiVersion: apps/v1
kind: Deployment
metadata:
  name: codegen-tgi
  labels:
    helm.sh/chart: tgi-0.1.0
    app.kubernetes.io/name: tgi
    app.kubernetes.io/instance: codegen
    app.kubernetes.io/version: "1.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tgi
      app.kubernetes.io/instance: codegen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tgi
        app.kubernetes.io/instance: codegen
    spec:
      securityContext: {}
      containers:
        - name: tgi
          env:
            - name: MODEL_ID
              value: ise-uiuc/Magicoder-S-DS-6.7B
            - name: PORT
              value: "8080"
            - name: NUMBA_CACHE_DIR
              value: /data
            - name: HF_TOKEN
              value: "{{ .Values.huggingfacehubApiToken }}"
          securityContext: {}
          image: "ghcr.io/huggingface/text-generation-inference:1.4"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: model-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
      volumes:
      - emptyDir:
          sizeLimit: 50Gi
        name: model-volume
