huggingfacehubApiToken: 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

llmUservice:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/test-paulina/llm-tgi
    tag: "latest"

servingRuntime:
  name: model
  namespace: codegen-helm

global:
  clusterDomain: rojo.igk.internal
  namespace: codegen-helm

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

serviceAccountName: codegen-sa

rbac:
  roles:
    - name: codegen-rhoai-role
      createRole: true
      apiGroups:
        - '""'
        - '"apps"'
        - '"batch"'
        - '"machineconfiguration.openshift.io"'
        - '"rbac.authorization.k8s.io"'
        - '"security.openshift.io"'
        - '"datasciencecluster.opendatahub.io"'
        - '"operator.knative.dev"'
        - '"build.openshift.io"'
      scope:
        cluster: true
      resources:
        - namespaces
        - secrets
        - datascienceclusters
        - clusterrolebindings
        - knativeservings
        - jobs
        - buildconfigs
        - builds
        - buildconfigs/instantiate
      verbs:
        - "create"
        - "get"
        - "list"
        - "patch"
        - "update"
        - "use"
        - "watch"
    - name: codegen-rhoai-role-mcp-label
      createRole: true
      apiGroups:
        - '"machineconfiguration.openshift.io"'
      scope:
        cluster: true
      resources:
        - machineconfigpools
        - machineconfigs
      verbs:
        - "get"
        - "list"
        - "patch"
        - "watch"
  roleBindings:
    - name: codegen-rhoai-rolebind
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: codegen-sa
        namespace: codegen-helm
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: codegen-rhoai-role
    - name: codegen-rhoai-role-mcp-label
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: codegen-sa
        namespace: codegen-helm
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: codegen-rhoai-role-mcp-label
