apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ui-server
  name: ui-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui-server
  template:
    metadata:
      labels:
        io.kompose.service: ui-server
    spec:
      initContainers:
        - name: copy-ui-to-workdir
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          command:
            - /bin/bash
            - -c
          args:
            - |
              cp -v -r /home/user/* /tmp/temp-data/
          volumeMounts:
            - name: temp-data
              mountPath: /tmp/temp-data
      containers:
        - env:
            - name: HOME
              value: /tmp/temp-data
            - name: BASIC_URL
              value: "http://codegen-{{ .Values.namespace }}.apps.{{ .Values.global.clusterDomain }}/v1/codegen"
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          name: ui-server
          ports:
            - containerPort: 5173
              protocol: TCP
          workingDir: /tmp/temp-data/svelte
          volumeMounts:
            - name: temp-data
              mountPath: /tmp/temp-data
      restartPolicy: Always
      volumes:
        - name: temp-data
          emptyDir: {}
