apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ui-server
  name: ui-server
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  selector:
    io.kompose.service: ui-server
